<div class="row">
    <?="<p>".$this->message."</p>"?>
    <div id='home_content'>
        <article>
            <h1>Slacklining For Beginners – Step by Step</h1>
            <p>If you just started (or plan to start) with slacklining, you have come to the right place. Here you will find all the information, tips and advice you'll need to learn how to slackline quickly and easily, one step at a time.</p>
            <ul>
                <li>1. <a href='#what-is-slackline'>What is Slacklining</a></li>
                <li>2. <a href='/gear/slackline'>Choose the best line for your needs</a></li>
                <li>3. <a href='/setup'>How to set it up</a></li>
                <li>4. <a href='/blog/howto'>Learn how to walk the line</a></li>
            </ul>
        </article>
        <article id='what-is-slackline'>
            <h2>What is slackline</h2>
            <p>
                <img src='/img/what_is_slackline.jpg' class='what_is_slackline_img' />
                Slacklining can be described as walking, balancing or doing various tricks on a line tensioned between two anchors (trees most often). It may seem similar to tightrope walking, however the slackline webbing is flat and broader (1 or 2 inches for example), and the line itself is not perfectly tight – rather stretchy and dynamic.<br><br>

                Thanks to these features, the versatility is really high and that's what makes this sport so popular. Slackliners are not limited to just walking or balancing – you can perform a wide variety of tricks, jumps or bounces, you can use the line for static poses, fitness and yoga. Or even try the advanced branches of slacklining – longlining and highlining. And it's a great plaything for kids as well ;)
            </p>
        </article>
        <article id='slackline_disciplines'>
            <h2>Slacklining disciplines</h2>
            <p class='discipline'>
                <img src='/img/trickline.jpg'/>
                <h4>Trickline</h4>
                – (also called lowline as it is set up low to the ground) is connected with all the static poses, tricks, jumps and bounces. It's very popular, thanks to the fact that you don't need any special and expensive equipment, just a slackline kit which can be purchased for about $50-100 (and is very easy to set up).
            </p><br><br>
            <p class='discipline'>
                <img src='/img/waterline.jpg'/>
                <h4>Longline</h4>
                – involves walking a line longer than 30 meters (98 ft) – but the number can get much higher, the current world record is 1620 ft! Longlining is a real challenge for anyone's skills – as the line gets longer, the sag and also swinging increase. Also more sophisticated (and expensive) rigging methods have to be used to achieve the proper tension of the line.
            </p><br><br>
            <p class='discipline'>
                <img src='/img/highline.jpg'/>
                <h4>Highline</h4>
                – the pinnacle of slacklining, a line set up high above ground – not only physically but also extremely mentally challenging. The eventual fall would be fatal so a climbing harness with a leash connected to the line is necessary. Quality of the rigging system is extremely important as well.
            </p><br><br>
        </article>
    </div>
</div>