<div class="row">
    <div class='span3'>
        <ul class='green_circle'>
            <?php 
                foreach ($this->linkovi as $value) {
                    echo "$value";
                }
            ?>
        </ul>
    </div>
    <div class="span9">
        <h2>How To Set Up a Slackline</h2>
            <p class='setup_p'>Before you start walking, it is necessary to set the line up properly. At this section, we will go through all the main rigging methods you may come across, and use videos to explain the setup techniques.</p>
            <br><br>
            <h4>Advice for beginners</h4>
            <ul>
            <li><p class='setup_p'>Find two strong and healthy trees, greater than 12" in diameter and about 10-15 feet apart – you want to start with a shorter line as it is more stable and easier to walk. If there are no trees available in your location, read how to set the slackline up without them.</p></li>

            <li><p class='setup_p'>There shouldn't be any dangerous object on the ground, like sharp rocks for example (particularly when walking barefoot). A lawn, sand or similar soft ground is perfect. If there is no other possibility, you can cover the harsh ground with old mattresses or similar stuff.</p></li>

            <li><p class='setup_p'>Set the line low to the ground (knee height) and very tight – hard lines are better for beginners as they are easier to walk than loose slacklines.</p></li>

            <li><p class='setup_p'>Don't forget the tree protection. Also take the line down after each session, don't leave it up for more than a few hours for example – that not only protects the vascular system of the tree under the bark, but also helps to preserve your slackline's condition.</p></li>
            </ul>
            <br><br>
            <div class='company_setup'>
                <h4>Gibbon Slacklines Setup</h4>
                <img src='/img/setup/gibbon_logo.png' alt='gibbon logo' class='company_setup_img' />
            </div>
            <p>The Gibbon system is one of the easiest available today – the only thing you have to do is anchor both parts to the trees and join them with the ratchet. Releasing a Gibbon slackline is also very easy: You pull up the safety lever (releasing the handle), open the handle completely and release the tension by one more push. It's covered in the video as well.
            </p>
            <div class='setup_video'><iframe src="https://www.youtube.com/embed/9YVs_s-xc6g" frameborder="0" allowfullscreen></iframe> </div>
            <br><br>

            <div class='company_setup'>
                <h4>Mammut Slackline Setup</h4>
                <img src='/img/setup/mammut_logo.png' alt='mammut logo' class='company_setup_img' />
            </div>
            <p>The Mammut setup is one of the more complicated methods. However, its advantage is that the ratchet never comes in contact with the walking line (so there is no danger of damaging it) and can be even removed after setup.
            </p>
           <div class='setup_video'><iframe src="https://www.youtube.com/embed/-eHqd6jjFzk" frameborder="0" allowfullscreen></iframe> </div><br><br>

           <div class='company_setup'>
                <h4>Carabiners Setup</h4>
                <img src='/img/setup/custom.png' alt='custom logo' class='company_setup_img' />
            </div>
            <p>The original method of rigging a slackline with climbing gear – it is the most difficult, takes the longest time and it's not easy to achieve a high tension (needed for tricks for example). However, everything you need is a webbing for the line, two loops of webbing for anchors and a few carabiners – which makes this method the least expensive.
            </p>
           <div class='setup_video'><iframe src="https://www.youtube.com/embed/MdDzz5H2VQA" frameborder="0" allowfullscreen></iframe> </div><br><br>
    </div>
</div>