<div class="row">
    <div class='span3'>
        <ul class='green_circle'>
            <?php 
                foreach ($this->linkovi as $value) {
                    echo "$value";
                }
            ?>
        </ul>
    </div>
    <div class="span9">
        <h1>Indoor set up slackline</h1>
        <p>You'll probably spend most of your slackline sessions outdoors, in the nature – however, there are situations when you'll appreciate an indoor setup. For example when it's raining (on the other hand, a lot of people love slacklining in the rain ;) ), in the winter or even in your office for short relaxation pauses.</p><br><br>
        <?php
            foreach ($this->elements as $value) {
                echo "<div id='".$value->getDivId()."'>
                            <h3>".$value->getName()."</h3>
                            <img src='/img/setup/indoor/".$value->getImg()."' alt='".$value->getName()."' class='img_setup' />
                            <p><b>For:</b> ".$value->getFor()."</p>
                            <p><b>Needed:</b> ".$value->getNeeded()."</p>
                            <p>
                                ".$value->getDescription()."
                            </p><br>
                            <div class='setup_video'>
                                <iframe src='".$value->getVideo()."' frameborder='0' allowfullscreen></iframe>
                            </div>
                        </div><div class='gap'></div>";
            }
        ?>
    </div>
</div>