<div class="row">
    <div class='span3'>
        <ul class='moify_navigation'>
            <li class='modify_action'><div>Add</div>
                <ul>
                    <li><a href='#newTrick'>Trick</a></li>
                    <li><a href='#newKit'>Slackline kit</a></li>
                    <li><a href='#newSlackline'>Slackline</a></li>
                    <li><a href='#newSetup'>Setup</a></li>
                </ul>
            </li>
            <li class='modify_action'><div>Edit</div>
                <ul>
                    <li><a href='#newTrick'>Trick</a></li>
                    <li><a href='#newKit'>Slackline kit</a></li>
                    <li><a href='#newSlackline'>Slackline</a></li>
                    <li><a href='#newSetup'>Setup</a></li>
                </ul>
            </li>
            <li class='modify_action'><div>Delete</div>
                <ul>
                    <li><a href='#newTrick'>Trick</a></li>
                    <li><a href='#newKit'>Slackline kit</a></li>
                    <li><a href='#newSlackline'>Slackline</a></li>
                    <li><a href='#newSetup'>Setup</a></li>
                </ul>
            </li>
            <?php
                if($this->rola=='2'){
                    echo "<li class='modify_action'><div>Users</div></li>";
                }
            ?>
            
        </ul>
    </div>
    <div class='span9' id='modifyContent'>
        <h3>Select your action to continue</h3>
    </div>
</div>
<div class="gap"></div>
<div class="gap"></div>