<div class="row">
    <div class='span3'>
        <ul class='moify_navigation'>
            <li class='modify_action'><div id='administrator_add'>Add / Edit</div>
                <ul>
                    <li><a href='#newMenu'>Menu</a></li>
                    <li><a href='#newTrickType'>Trick type</a></li>
                    <li><a href='#newTrickWeight'>Trick weight</a></li>
                    <li><a href='#newTrick'>Trick</a></li>
                    <li><a href='#newTrickWeightMark'>Trick weight mark</a></li>
                    <li><a href='#newGear'>Gear</a></li>
                    <li><a href='#newSlackline'>Slackline</a></li>
                    <li><a href='#newSetup'>Setup</a></li>
                    <li><a href='#newTypeSetup'>Setup type</a></li>
                    <li><a href='#newSlacklineRating'>Slackline rating</a></li>
                    <li><a href='#newBrand'>Brand</a></li>
                    <li><a href='#newDoneTrick'>Done tricks</a></li>
                    <li><a href='#newRoles'>Roles</a></li>
                    <li><a href='#newGearComments'>Gear comment</a></li>
                    <li><a href='#newSlacklineComments'>Slackline comment</a></li>
                </ul>
            </li>
            <li class='modify_action'><div id='administrator_remove'>Remove</div>
                <ul>
                    <li><a href='#newMenu'>Menu</a></li>
                    <li><a href='#newTrickType'>Trick type</a></li>
                    <li><a href='#newTrickWeight'>Trick weight</a></li>
                    <li><a href='#newTrick'>Trick</a></li>
                    <li><a href='#newTrickWeightMark'>Trick weight mark</a></li>
                    <li><a href='#newGear'>Gear</a></li>
                    <li><a href='#newSlackline'>Slackline</a></li>
                    <li><a href='#newSetup'>Setup</a></li>
                    <li><a href='#newTypeSetup'>Setup type</a></li>
                    <li><a href='#newSlacklineRating'>Slackline rating</a></li>
                    <li><a href='#newBrand'>Brand</a></li>
                    <li><a href='#newDoneTrick'>Done tricks</a></li>
                    <li><a href='#newRoles'>Roles</a></li>
                    <li><a href='#newGearComments'>Gear comment</a></li>
                    <li><a href='#newSlacklineComments'>Slackline comment</a></li>
                    <li><a href='#newUsers'>Users</a></li>
                </ul>
            </li>
            <li class='modify_action'><div id='administrator_user'>User</div></li>
        </ul>
    </div>
    <div class='span9' id='administration_content'>
        <h3>Select your action to continue</h3>
    </div>
</div>
<div class="gap"></div>
<div class="gap"></div>