<?php $this->placeholder("topArea")->captureStart();?>
    <div class="top-area">
        <!-- START BOOTSTRAP CAROUSEL -->
        <div id="my-carousel" class="carousel slide">
            <div class="carousel-inner">
                <div class="active item">
                    <img src="img/slider/front/slide1.jpg" alt="Line walking and balacing slackline" title="Line walking" />
                    <div class="carousel-caption countdown-caption">
                        <h3>Line walking and balacing</h3>
                    </div>
                </div>
                <div  class="item">
                    <img src="img/slider/front/slide2.jpg" alt="Line walking slackline" title="Line walking" />
                    <div class="carousel-caption countdown-caption">
                        <h3>Line walking</h3>
                    </div>
                </div>
                <div  class="item">
                    <img src="img/slider/front/slide3.jpg" alt="High line walking slackline" title="Highline walking" />
                    <div class="carousel-caption countdown-caption">
                        <h3>Highline walking</h3>
                    </div>
                </div>
                <div  class="item">
                    <img src="img/slider/front/slide4.jpg" alt="Waterline walking slackline" title="Waterline walking" />
                    <div class="carousel-caption countdown-caption">
                        <h3>Waterline walking</h3>
                    </div>
                </div>
            </div>
            <a class="carousel-control left" href="#my-carousel" data-slide="prev"></a>
            <a class="carousel-control right" href="#my-carousel" data-slide="next"></a>
        </div>
        <!-- END BOOTSTRAP CAROUSEL -->
    </div>
<?php $this->placeholder("topArea")->captureEnd();