         
        <p>Have you already bought your first line and set it up? Then it is time to learn how to walk it! We'll present you an effective technique to learn slacklining as quickly as possible, and also some helpful related tips.</p>

        <br><br>
        <h4>Positive Approach</h4>
        <p>Learning a new skill is always difficult at first – but don't worry! Remember learning how to ride a bike? Very frustrating in the beginning but really easy after some practice. And it's the same with slacklining.<br>
        So think positively, stay relaxed and have fun. Keep on trying and you will succeed – patience is the key.</p>
        <br><br>

        <h4>With our Without Shoes?</h4>
        <p>
            Mostly it is better to start barefoot as you'll get better contact with the line and learn faster. However, as you gain more skill and begin trying various tricks and stunts, you would probably switch to shoes to protect your feet when landing (also, wearing shoes becomes a necessity when the ground is not safe for landing barefoot).
            <br><br>
            When using shoes, tie the laces tightly so your feet don't wobble in them. Also check the sole for any stuck sharp rock pieces – they can damage the line.
        </p>
        <br><br>
        <h4>Video</h4>
        <p>
            <a href="http://www.gibbonslacklines.com/us/index.php?option=com_k2&view=item&id=323:frankie-najera&Itemid=408" target='_blank'>Frankie Najera</a> teaching you how to balance and walk on slackline. Frank Najera is part of <a href="http://www.gibbonslacklines.com/us/index.php?option=com_k2&view=item&layout=item&id=293&Itemid=69" target='_blank'>Gibbon slackline team</a>.
        </p>
        <div class='setup_video'>
            <iframe src="http://www.youtube.com/embed/2TzERkdNoyw" frameborder="0" allowfullscreen></iframe>
        </div>
        <br><br>
        <h4>1. Learn How to Balance</h4>

        <p>Frankie suggests to learn how to balance on the line prior to taking your first steps on it – and I agree. If you try walking on the line right away, most probably you'll end up with few hasty steps and then fall off. Just balancing on one leg is easier as you can use the other to leg to help you keep balance. So:</p>
        <ul class='green_circle'>
            <li>Position yourself near the middle of the slackline and place one foot on it – <b>inline, not across</b>.</li>
            <li>Keep your <b>arms overhead</b>, with elbows above your shoulders – do not wave them around your body and don't put them straight out to the sides. You don`t have any pole like tightrope walkers, the key is to shift weight to the sides with your arms (and leg when balancing).</li>
            <li>Keep your back straight (or even lean back a little) – when you bend forward, you'll tend to fall and make hasty, uncertain steps.</li>
            <li>As already mentioned, focus on something in front of you. Do not look under your feet.</li>
        </ul>
        <p>Practise your balance on one leg, count to 20 for example and then switch your legs. While doing so, keep the <b>basic slacklining position</b>:</p>
        <ul class='green_circle'>
            <li >Bend your knees slightly to lower your center of gravity and absorb the vibrations of the line. Don't worry, everyone wobbles when starting – after some practice your muscles will deal with it.</li>
            <li>Do not press against the line as it will start wobbling – rather keep your leg relaxed.</li>
            <li><b>Do not look under you feet</b>, focus rather on a single point in front of you, for example the anchor of the line or something on the tree – this will help you a lot with keeping balance.</li>
            <li>Raise your arms over your head and start</li>
        </ul>   
        <br><br>
        <h4>2. Learn How to Walk a Slackline</h4>
        <p>Once you learn how to keep balance on the slackline, try your first steps. Again, stay in the basic position described above.
            <br><br>
            Plus there are few more tips:
        </p>
        <ul class='green_circle'>
            <li >Walk with your feet straight on the line (not across) and your hips, chest and head straight against the anchor. Don't worry, you will develop other styles of walking and jumping later on ;)</li>
            <li>When the line starts swinging, try lowering your center of gravity even more to stabilize your body.</li>
            <li>Don't run, take your time and enjoy the new type of movement you are just learning.</li>
            <li>Even if you lose the balance, try to stay on the line as long as possible before you fall – that helps developing your muscles and skills as soon as possible.</li>
            <li>And if you still experience problems, ask a friend to walk with you and give you a helping hand (that's useful particularly for kids). Another option is to have someone sitting on the other side of the line – it will make it more stable</li>
        </ul>
        <br><br>
        <h4>3. What next?</h4>

        <p>Congratulations! You've just mastered the first slacklining skill – balancing and walking. But just walking the line again and again will become boring after some time – so what are the other possibilities?</p>
         <ul class='green_circle'>
            <li>Start with basic tricks as soon as possible – turning around, walking backwards, jump start and others. Your skills will improve much faster and you'll quickly fell in love with tricklining.</li>
            <li>Another option is Longlining – walking a line longer than 30 meters (98 ft). You'll need a special equipment, however, it will open a whole new world of slacklining possibilities you can enjoy.</li>
            <li>And you can even progress into Highlining – balancing on a line high above the ground, set up between two rocks or buildings.</li>
        </ul>
        <p>And remember, slacklining is a social sport! So join some group in your area, or found a new one with your friends – you can get the best experience, knowledge and tips during slackline sessions with your friends on the line</p>
        <div class="gap"></div>